<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>HaYTooL_Wallpaper</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\IniHelper.cs" />
  </ItemGroup>

</Project>
