<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>HaYTooL_Wallpaper</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>..\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\IniHelper.cs" />
  </ItemGroup>

</Project>
